# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Th0GuveKdHTrv9ZP3s1VCRSi2iLEZV9Q
"""

import Levenshtein

def calculate_similarity(text1, text2):
    return 1 - Levenshtein.distance(text1.lower(), text2.lower()) / max(len(text1), len(text2))

def check_plagiarism(text1, text2, threshold=0.8):
    similarity = calculate_similarity(text1, text2)
    if similarity >= threshold:
        print(f"Similarity: {similarity:.2f} - The texts may be plagiarized.")
    else:
        print(f"Similarity: {similarity:.2f} - The texts are not plagiarized.")

if __name__ == "__main__":
    # Example usage:
    text1 = "This is a sample text that will be compared."
    text2 = "This is another sample text that will be compared for plagiarism."

    check_plagiarism(text1, text2)